config/routes.rb
Rails.application.routes.draw do
  
  get 'posts/searchindex', :as=> :posts_searchindex
  
  get 'comments/index'

  get 'comments/model'

  get 'comments/helper'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  root 'posts#main'
  
  get 'posts/index'
  
  get 'posts/index2'
  
  get 'posts/index3'
  
  get 'posts/main'

  get 'posts/new' => 'posts#new' , as:'new_post'

  get 'posts/create'
  
  get 'posts/show'
  
  post 'posts' => 'posts#create'
  

  
  
  resources 'posts' do
    resources 'comments'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.nil?
      #   can :read, :all
      # else 
      #   can [:read, :create], :all
      #   can [:update, :destroy], Post, user_id: user_id
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
        
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
#   resourcify
#   include Authority::Abilities
    belongs_to :category
    has_many :comments
    belongs_to :user
    
    def self.search(search) 
         if search 
           where('content LIKE ?', "%#{search}%") || where('title LIKE ?', "%#{search}%") 
         else 
           all 
         end 
    end
    
    
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
# include Authority::UserAbilities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  def configure_permitted_parameters 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_id]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_id]) 
  end

  # # Send 'em back where they came from with a slap on the wrist
  # def authority_forbidden(error)
  #   Authority.logger.warn(error.message)
  #   redirect_to request.referrer.presence || root_path, :alert => 'You are not authorized to complete that action.'
  # end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)
      @comment.user = current_user
      @comment.save
      
      redirect_to post_path(@post)
      
 end
   
  
  def edit
   @post = Post.find(params[:post_id])
   @comment = Comment.find(params[:id])
   authorize! :update, @comment
  end

  def update
    @post = Post.find(params[:id])
    @post.update(content_params)
    
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    # @content.delete #only content
    @comment.destroy #content 자식들까지 삭제
    
    redirect_to @post # 'http://~' 절대경로
    # redirect_to contents_path #'/contents' 상대경로
  end
  
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # load_and_authorize_resource
  
 
  def index
    @posts = Post.all
    @posts_netflix = @posts.where(category_id: 1)
    
  end
  
  def index2
    @posts = Post.all
    
    @posts_dark = @posts.where(category_id: 3)
  end

  def index3
    @posts = Post.all
    @posts_blacklist = @posts.where(category_id: 2)
  end
  
  def show
    @post = Post.find(params[:id])
    @posts = Post.all
  end

  def new
    @post = Post.new
    @categories = Category.all
    # authorize! :write, @post
  end

  def create
    post = Post.new(post_params)
    post.save
    
    redirect_to :root
  
  end
  
  def edit
    # authorize_action_for @post
     @post = Post.find(params[:id])
  
  end

  def update
    @post = Post.find(params[:id])
    @post.update(content_params)
    
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy 
    
    redirect_to :root
  end
  
  def searchindex
    @posts = Post.all.reverse
    @posts = Post.search(params[:search])
    @post = Post.new
    @categories = Category.all 
    
  end
  
  
  private
    def post_params
    params.require(:post).permit(:title, :content, :category_id)
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
#     def icon(shape)
#   "<span class='glyphicon glyphicon-#{shape}'></span>".html_safe
#     end
end

app/helpers/comments_helper.rb
module CommentsHelper

    
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<!--  부트스트랩-->
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!--이 아래부터 부트스트랩-->
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!--이 위까지 부트스트랩-->
<style>
.navbar.transparent.navbar-inverse .navbar-inner {
   background: rgba(0,0,0,0.4);
}
</style>  

  </head>
  
<body>
<div class="itsimportant">
      <nav class="navbar navbar-expand-lg navbar-light bg-faded" >
        <a class="navbar-brand" href="https://netflix-juan1104.c9users.io"><img alt="" src="/assets/brand.png"></a>
      
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent"  >
          <ul class="navbar-nav mr-auto navbar-left">
            <li class="nav-item active">
              <a class="nav-link" href="https://netflix-juan1104.c9users.io">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://netflix-juan1104.c9users.io/posts/index">NETFLIX</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://netflix-juan1104.c9users.io/posts/index3">BLACKLIST</a>
            </li>
            
              <li class="nav-item">
                <a class="nav-link" href="https://netflix-juan1104.c9users.io/posts/index2"> &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;</a>
              </li>
           
          </ul>
          
        
          <ul class="navbar-nav justify-content-end navbar-right">
              <% if user_signed_in? %>
                  <span class="navbar-text">
                      <strong><%= current_user.email%></strong>님 환영합니다!
                  </span>
                
                  <li class="nav-item">
                      <!--<a class="nav-link" href="https://netflix-juan1104.c9users.io/users/sign_out">로그아웃</a>-->
                      <%= link_to '로그아웃', destroy_user_session_path, :method => :delete %>
              
                  </li>
              <% else %>
                  <li class="nav-item">
                      <a class="nav-link" href="https://netflix-juan1104.c9users.io/users/sign_in">로그인</a>
        
                      <!--</%= link_to '로그인', new_user_session_path %>-->
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="https://netflix-juan1104.c9users.io/users/sign_up">회원가입</a>
                    
                      <!--</%= link_to '회원가입', new_user_registration_path %>-->
                  </li>
              <% end %>
          </ul>
      
        </div>
      </nav>
</div>    
      
      
        


<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<style>

* {
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  margin: auto;
}

.selct{
        box-sizing: border-box;
    border: 2px solid #f69e6d;
}

.newpost_title{
    width: 100%;
    padding: 0px 1px;
    /*margin: 8px 0;*/
    margin: auto;
    justify-content:center;
    width: max-content;
}

input[type=text] {
    width: 100%;
    padding: 12px 20px;
    /*margin: 8px 0;*/
    box-sizing: border-box;
    border: 2px solid #f69e6d;
    border-radius: 10px
}

.newpost_body{
    /*width: 100%;*/
    /*margin:0;*/
    /*padding:0;*/
    display:flex;
    flex-direction:column;
    align-items:center;
    /*border: 2px solid orange;*/
    border-radius: 10px;
    width: max-content;
    margin: auto;
}

textarea {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #f69e6d;
    border-radius: 10px;
    /*background-color: #f8f8f8;*/
    font-size: 16px;
    resize: none;
}

/*.submit{*/
/*    width: 100%;*/
/*    margin:0;*/
/*    padding:0;*/
/*    display:flex;*/
/*    flex-direction:column;*/
/*    justify-content:center;*/
/*}*/

.main{
    margin:0;
    text-align:center;
}

/*.board_section {*/
/*    width : 1000px;*/
/*    margin: 5% auto;*/
    /*margin-top:;*/
/*}*/


.category{
     justify-content:center;
     margin: 0;
}

input[type='submit']{
    border:none;
    background-color:#f69e6d;
    color:white;
    font-size:15px;
    padding:3px 10px;
    border-radius: 15px;
    width: 50%
    margin: auto;
    /*height: 10px;*/
    horizontal-align:middle
    }

</style>

<body>
<section class = "board_section" >
        <%= form_for @post do |f| %>
            <%= f.text_field :title,:size=>"50" %><br>
            <%= f.text_area :content, cols: "80", rows: "10" %><br>
            <%= f.submit %>
        <%end%>
</section>
</body>

app/views/posts/index.html.erb
<!--권한부여-->
<!--</%= link_to icon('eye-open'), post %>&nbsp;-->
<!--</% if user_signed_in? %>-->
<!--  </%= link_to icon('edit'), edit_post_path(post) if post.updatable_by? current_user %>&nbsp;-->
<!--  </%= link_to icon('trash'), post, method: :delete, data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>-->
<!--</% end %>-->
<!--권한부여-->
<head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <style>
@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
.introduction{
    margin: auto;
    margin-left: 210px;
    
}

.aaa{
    font-weight: bold;
    font-size: 40px;
}
body { 
    font-family: 'Jeju Gothic', sans-serif;
    font-size : 20px;
}
    
    
    .right{
        float :right;
        right :0px;
        padding: 10px;
        padding-right: 205px;
    }
        .table1{
            
            margin :auto;
            width: 70%;
            text-align: center;
        }
        .m1{
            text-align :center;
        }
        




    </style>
</head>

<body>
    <div class = introduction>
        <div class = "aaa">
            NETFLIX
        </div>
        <div class = "bbb">
            NETFLIX 계정을 공유하는 게시판입니다
        </div>
    </div>
<div class="right">
    <div class="search">
    <%= form_tag posts_searchindex_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder:"제목/내용으로 검색" %>
          <%= submit_tag "검색", :name => nil %> 
    <% end %>
     </div>
</div>
    
    
    



</div>
<div class="table1">

    <table class="table table-hover">
         <thead>
            <tr>
                 <th width="5%", style="text-align:center">번호</th>
                 <th width="55%", style="text-align:center">제목</th>
                 <th width="15%", style="text-align:center">글쓴이</th>
            </tr>
        </thead>
        <tbody>
        <% @posts_netflix.each do |p| %>

            <tr>
                <td width="5%"> <%= p.id %></td>
                <td width="55%"><a href='<%= post_path(p.id)%>'><%= p.title %></a></td>
                <td width="15%"><%= p.email %></td>
            </tr>
            <% end %>
        
        </tbody>    
    </table>
</div>
<div class="right">
    
    <button type="button" class="btn btn-default"><%= link_to '글쓰기', '/posts/new' %></button>
</div>
<div class="m1">
    <br><br><br><br>
<button type="button" class="btn btn-default">
<%=link_to '메인으로' , root_path %>
</button>
</div>


</body>

app/views/posts/index2.html.erb
<!--권한부여-->
<!--</%= link_to icon('eye-open'), post %>&nbsp;-->
<!--</% if user_signed_in? %>-->
<!--  </%= link_to icon('edit'), edit_post_path(post) if post.updatable_by? current_user %>&nbsp;-->
<!--  </%= link_to icon('trash'), post, method: :delete, data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>-->
<!--</% end %>-->
<!--권한부여-->
<head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <style>
@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
.introduction{
    margin: auto;
    margin-left: 210px;
    
}

.aaa{
    font-weight: bold;
    font-size: 40px;
}
body { 
    font-family: 'Jeju Gothic', sans-serif;
    font-size : 20px;
}
    
    
    .right{
        float :right;
        right :0px;
        padding: 10px;
        padding-right: 205px;
    }
        .table1{
            
            margin :auto;
            width: 70%;
            text-align: center;
        }
        .m1{
            text-align :center;
        }
        




    </style>
</head>

<body>
    <div class = introduction>
        <div class = "aaa">
            HIDDEN
        </div>
        <div class = "bbb">
            NETFLIX 외의 계정을 불법적으로 공유하는 게시판입니다<br>
            계정의 공유로 인해 발생하는 피해에 대해 저희는 책임을 지지 않습니다
        </div>
    </div>
<div class="right">
    <div class="search">
    <%= form_tag posts_searchindex_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder:"제목/내용으로 검색" %>
          <%= submit_tag "검색", :name => nil %> 
    <% end %>
     </div>
</div>
    
    
    



</div>
<div class="table1">

    <table class="table table-hover">
         <thead>
            <tr>
                 <th width="5%", style="text-align:center">번호</th>
                 <th width="55%", style="text-align:center">제목</th>
                 <th width="15%", style="text-align:center">글쓴이</th>
            </tr>
        </thead>
        <tbody>
        <% @posts_dark.each do |p| %>

            <tr>
                <td width="5%"> <%= p.id %></td>
                <td width="55%"><a href='<%= post_path(p.id)%>'><%= p.title %></a></td>
                <td width="15%"><%= p.email %></td>
            </tr>
            <% end %>
        
        </tbody>    
    </table>
</div>
<div class="right">
    
    <button type="button" class="btn btn-default"><%= link_to '글쓰기', '/posts/new' %></button>
</div>
<div class="m1">
    <br><br><br><br>
<button type="button" class="btn btn-default">
<%=link_to '메인으로' , root_path %>
</button>
</div>


</body>

app/views/posts/index3.html.erb
<!--권한부여-->
<!--</%= link_to icon('eye-open'), post %>&nbsp;-->
<!--</% if user_signed_in? %>-->
<!--  </%= link_to icon('edit'), edit_post_path(post) if post.updatable_by? current_user %>&nbsp;-->
<!--  </%= link_to icon('trash'), post, method: :delete, data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>-->
<!--</% end %>-->
<!--권한부여-->
<head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <style>
@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
.introduction{
    margin: auto;
    margin-left: 210px;
    
}

.aaa{
    font-weight: bold;
    font-size: 40px;
}
body { 
    font-family: 'Jeju Gothic', sans-serif;
    font-size : 20px;
}
    
    
    .right{
        float :right;
        right :0px;
        padding: 10px;
        padding-right: 205px;
    }
        .table1{
            
            margin :auto;
            width: 70%;
            text-align: center;
        }
        .m1{
            text-align :center;
        }
        




    </style>
</head>

<body>
    <div class = introduction>
        <div class = "aaa">
            BLACKLIST
        </div>
        <div class = "bbb">
            약속을 어긴 사람들의 명단을 신고하고 공유하는 게시판입니다
        </div>
    </div>
<div class="right">
    <div class="search">
    <%= form_tag posts_searchindex_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder:"제목/내용으로 검색" %>
          <%= submit_tag "검색", :name => nil %> 
    <% end %>
     </div>
</div>
    
    
    



</div>
<div class="table1">

    <table class="table table-hover">
         <thead>
            <tr>
                 <th width="5%", style="text-align:center">번호</th>
                 <th width="55%", style="text-align:center">제목</th>
                 <th width="15%", style="text-align:center">글쓴이</th>
            </tr>
        </thead>
        <tbody>
        <% @posts_blacklist.each do |p| %>

            <tr>
                <td width="5%"> <%= p.id %></td>
                <td width="55%"><a href='<%= post_path(p.id)%>'><%= p.title %></a></td>
                <td width="15%"><%= p.email %></td>
            </tr>
            <% end %>
        
        </tbody>    
    </table>
</div>
<div class="right">
    
    <button type="button" class="btn btn-default"><%= link_to '글쓰기', '/posts/new' %></button>
</div>
<div class="m1">
    <br><br><br><br>
<button type="button" class="btn btn-default">
<%=link_to '메인으로' , root_path %>
</button>
</div>


</body>

app/views/posts/new.html.erb
<!DOCTYPE html>
<style>



select{
    overflow:hidden;
    width:350px;
    -moz-border-radius: 9px 9px 9px 9px;
    -webkit-border-radius: 9px 9px 9px 9px;
    border-radius: 9px 9px 9px 9px;
    box-shadow: 1px 1px 11px #330033;
    background: #f69e6d; 
}

.newpost_title{
    width: 100%;
    padding: 0px 1px;
    /*margin: 8px 0;*/
    margin: auto;
    justify-content:center;
    width: max-content;
}

input[type=text] {
    width: 100%;
    padding: 12px 20px;
    /*margin: 8px 0;*/
    box-sizing: border-box;
    box-shadow: 1px 1px 11px #330033;
    border: 2px solid #f69e6d;
    border-radius: 10px
}

.newpost_body{
    /*width: 100%;*/
    /*margin:0;*/
    /*padding:0;*/
    display:flex;
    flex-direction:column;
    align-items:center;
    /*border: 2px solid orange;*/
    border-radius: 10px;
    width: max-content;
    margin: auto;
}

textarea {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #f69e6d;
    border-radius: 10px;
    /*background-color: #f8f8f8;*/
    font-size: 16px;
    resize: none;
     box-shadow: 1px 1px 11px #330033;
}

.main{
    margin:0, 0, 0, 10;
    text-align:center;
}

.board_section {
     margin: 5% auto;
}


.category{
     justify-content:center;
     margin: 0;
}

input[type='submit']{
    border:none;
    background-color:#f69e6d;
    color:white;
    font-size:15px;
    padding:3px 10px;
    border-radius: 15px;
    width: 50%
    margin: auto;
    /*height: 10px;*/
    display: inline-block 
    text-align: center;
    margin: auto !important;
    box-shadow: 1px 1px 11px #330033;
    }
    


</style>


<html>
    
    <body>
<section class = "board_section" >
<br><br><br><br><br>
<%= form_for @post do |f| %>
    <div class = "select_box">
    <center> <%= f.select :category_id, options_from_collection_for_select(@categories,"id", "name") %> </center><br><br>
    </div>
    <div class="newpost_title">
    <%= f.text_field :title, :size=>"97", placeholder: '제목을 입력해주세요'  %><br>
    </div> <br>
     <div class="newpost_body">
    <%= f.text_area :content, placeholder: '내용을 입력해주세요', cols: "100", rows: "10",maxlength:3000 %>
   
    </div>
    <br>
    
        <center> <%= f.submit '올리기'%> </center>
     
    <br><br>
<% end %>
</section>
<div class = "main">
<%=link_to '메인으로' , root_path %>
</div>
<br><br><br><br><br>
</body>
</html>

 

app/views/posts/searchindex.html.erb
<head>
    <style>
        .right{
        float :right;
        right :0px;
        padding: 10px;
        padding-right: 205px;
    }
        .table1{
            
            margin :auto;
            width: 70%;
            text-align: center;
        }
    </style>
</head>

<div class="wholebox">


    
    <img src="/assets/freecon.png" >
    <br>
    
<%= link_to '목록으로 돌아가기', posts_path %>
<br>

<div class="search">
<%= form_tag posts_searchindex_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], placeholder:"제목/내용/작성자" %>
      <%= submit_tag "Search", :name => nil %>
<% end %>
</div><br><br>
    
<br>
<div class="table1">
    <table>
      <thead>
            <tr>
             <th width="5%", style="text-align:center">번호</th>
             <th width="55%", style="text-align:center">제목</th>
            </tr>
      </thead>
      <tbody>
              <% @posts.each do |post| %>
              <tr>
                    <td width-"5%"> <%= post.id %></td>
                    <td width="55%"><a href='<%= post_path(post)%>'><%= post.title %></a></td>
              </tr>
              <%end%>
      </tbody>
    </table> 
</div>
    </div>